LIBJANSSON_INCLUDE="/home/madcat/Devel/ECHMET/jansson-bin/include"
LIBJANSSON_BIN="/home/madcat/Devel/ECHMET/jansson-bin/lib/libjansson.a"
ECL_INCLUDE="/home/madcat/Devel/ECHMET/ECHMETCoreLibs-bin/include/ECHMET/CoreLibs"
ECL_BIN="/home/madcat/Devel/ECHMET/ECHMETCoreLibs-bin/lib"
LEMNG_INCLUDE="/home/madcat/Devel/ECHMET/LEMNG-bin/include/ECHMET/LEMNG"
LEMNG_BIN="/home/madcat/Devel/ECHMET/LEMNG-bin/lib"
