#ifndef ECHMET_LEMNG_LEMNG_TRACER_H
#define ECHMET_LEMNG_LEMNG_TRACER_H

#include "echmet_tracer.h"

enum class LEMNGTracing {
	MAKE_CZE_SYSTEM_ERR,
	EVAL_INIT_ERR,
	EVAL_PROGRESS_ERR,
	CALC_OBJECT_CONSTRUCTION,
	CALC_COMMON_CALC_SOLPROPS_PROGRESS,
	CALC_COMMON_CALC_SOLPROPS_ITERS,
	CALC_COMMON_CALC_SOLPROPS_EQ_COMP,
	CALC_COMMON_CALC_SOLPROPS_ION_MOBS,
	CALC_COMMON_CALC_SOLPROPS_EFF_MOBS,
	CALC_COMMON_CALC_SOLPROPS_CONDUCTIVITY,
	CALC_MATRIX_M1_DIMS,
	CALC_MATRIX_M2_DIMS,
	CALC_MATRIX_M1_UICIF_BLOCK,
	CALC_MATRIX_M1_UICIF_INTERMEDIATE,
	CALC_MATRIX_M1_ROW_BLOCK,
	CALC_MATRIX_M1_OUTPUT,
	CALC_MATRIX_M2_OUTPUT,
	CALC_MATRIX_DM1_INPUT,
	CALC_MATRIX_DM1_UICIDKDC,
	CALC_MATRIX_DM1_UIDCIDCJ,
	CALC_MATRIX_DM1_KRD,
	CALC_MATRIX_DM1_ROW_BLOCK,
	CALC_MATRIX_DM1_OUTPUT,
	CALC_MATRIX_DM2_OUTPUT,
	CALC_LIN_PROGRESS,
	CALC_LIN_MFIN,
	CALC_LIN_ZONE_TAINTED,
	CALC_NONLIN_PROGRESS,
	CALC_NONLIN_NEIGHBOUR_FORMS_LOOKUP,
	CALC_NONLIN_NERNST_EINST_INPUT,
	CALC_NONLIN_DIFFCOEFF_TERM_C_SUM,
	CALC_NONLIN_DIFFCOEFF_TERM_C_V,
	CALC_NONLIN_DIFFCOEFF_TERM_C_INTER2,
	CALC_NONLIN_DIFFCOEFF_TERM_D_SUM,
	CALC_NONLIN_DIFF_MATRIX,
	CALC_NONLIN_DIFF_PARAMS_MATRIX,
	EFGPLOT_INPUT_PARAMS,
	CALC_EIGENMOBS,
	EFGPLOT_ZONE_ENVELOPE,
	__LAST
};
ECHMET_MAKE_TRACEPOINT_IDS(LEMNGTracing, MAKE_CZE_SYSTEM_ERR, __LAST)

#endif // ECHMET_LEMNG_LEMNG_TRACER_H
